name: app-action
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  webapp-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - run: node --version
      - run: npm --version 
      - run: npm install
      - run: npm test

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.3"
      - name: Run `packer init`
        id: init
        run: "packer init ./packer-file.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./packer-file.pkr.hcl"